$ProjectFolder = 'C:\job\project\PhotoHash'
#$PathToMySQLdll = "$ProjectFolder\dll\MySql.Data.dll"
$PathToMySQLdll = "c:\temp\MySql.Data.dll"
$IPaddressOfMySQLserver = '10.23.129.7'
$rootDBuser = "sqladmin"
$rootDBpass = "sqladminpass"
$DBuser = "phunicuser"
$DBpass = "phunicpass"
$DBname = "PHUnic"
$LogProcessingErrors = "$ProjectFolder\log\ph-errors.txt"
$FlagDBfound = $false
#$Molotilka = "e:\exch\father migration\свадьба Наташи","e:\exch\father migration\С телефона вацап\фото 13.03.2018\WhatsApp Images","e:\exch\father migration\С телефона вацап\WhatsApp Images","e:\exch\father migration\С телефона вацап\Camera","e:\exch\father migration\С телефона асеr\WhatsApp Images","e:\exch\father migration\С телефона асеr\Camera","e:\exch\father migration\Ремонт у Виталия","e:\exch\father migration\двор","e:\exch\father migration\OK","e:\exch\father migration\Camera Uploads","e:\exch\father migration\100MEDIA"
#$Molotilka = "E:\h-fs\foto", "e:\photocollect", "E:\NOKIA", "E:\h-fs\ФОТО ИЗМЕНЕННОЕ", "E:\h-fs\эвакуация", "E:\ph"
$Molotilka = "E:\h-fs\foto", "e:\photocollect", "E:\NOKIA", "E:\h-fs\ФОТО ИЗМЕНЕННОЕ", "E:\h-fs\эвакуация", "E:\ph","e:\exch\father migration\свадьба Наташи","e:\exch\father migration\С телефона вацап\фото 13.03.2018\WhatsApp Images","e:\exch\father migration\С телефона вацап\WhatsApp Images","e:\exch\father migration\С телефона вацап\Camera","e:\exch\father migration\С телефона асеr\WhatsApp Images","e:\exch\father migration\С телефона асеr\Camera","e:\exch\father migration\Ремонт у Виталия","e:\exch\father migration\двор","e:\exch\father migration\OK","e:\exch\father migration\Camera Uploads","e:\exch\father migration\100MEDIA","e:\ph1"
#$Molotilka = "e:\ff"
$PHUnicPhotoPath = "D:\PHUnicPhoto"
$PHUnicVideoPath = "D:\PHUnicVideo"
$FilterSetVideo = "*.avi","*.mp4","*.mpg","*.mpeg","*.wmv","*.mov","*.mod","*.mts","*.3gp"
$FilterSetPhoto = "*.bmp","*.jpg","*.jpeg","*.png","*.tif","*.tiff","*.gif"
$FilterCommonSet = $FilterSetVideo + $FilterSetPhoto
$FilterMovMod = ".mov",".mod",".mts",".3gp"
$DoubleExtension = "ph-double"
$MovModExtension = "video-converted"
$sha256hashRenameLength = 6
$FilterMovFiles = "*.mov"
$PathToFFMPEG = "C:\temp\ffmpeg-20200429-280383a-win64-static\bin"
$FlagCheckUnicVault = $False